In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("pokedex_markdown.csv")
df.head()

,Dex Number,Name,Generation,Status,Species,Stat Total,HP,Attack,Defense,Sp. Attack,Sp. Defense,Speed,Type,Ability,Hidden Ability,Image
0,1,Bulbasaur,1,Normal,Seed Pokémon,318,45,49,49,65,65,45,![/assets/type_icons/Grass_Type_Icon.svg](/ass...,Overgrow,Chlorophyll,![/assets/home_images/bulbasaur.png](/assets/h...
1,2,Ivysaur,1,Normal,Seed Pokémon,405,60,62,63,80,80,60,![/assets/type_icons/Grass_Type_Icon.svg](/ass...,Overgrow,Chlorophyll,![/assets/home_images/ivysaur.png](/assets/hom...
2,3,Venusaur,1,Normal,Seed Pokémon,525,80,82,83,100,100,80,![/assets/type_icons/Grass_Type_Icon.svg](/ass...,Overgrow,Chlorophyll,![/assets/home_images/venusaur.png](/assets/ho...
3,3,Mega Venusaur,1,Normal,Seed Pokémon,625,80,100,123,122,120,80,![/assets/type_icons/Grass_Type_Icon.svg](/ass...,Thick Fat,-,![/assets/home_images/venusaur-mega.png](/asse...
4,4,Charmander,1,Normal,Lizard Pokémon,309,39,52,43,60,50,65,![/assets/type_icons/Fire_Type_Icon.svg](/asse...,Blaze,Solar Power,![/assets/home_images/charmander.png](/assets/...

In [6]:
mons = ["Charmander", "Pikachu", "Squirtle", "Bulbasaur"]
df[df["Name"].isin(mons)]

,Dex Number,Name,Generation,Status,Species,Stat Total,HP,Attack,Defense,Sp. Attack,Sp. Defense,Speed,Type,Ability,Hidden Ability,Image
0,1,Bulbasaur,1,Normal,Seed Pokémon,318,45,49,49,65,65,45,![/assets/type_icons/Grass_Type_Icon.svg](/ass...,Overgrow,Chlorophyll,![/assets/home_images/bulbasaur.png](/assets/h...
4,4,Charmander,1,Normal,Lizard Pokémon,309,39,52,43,60,50,65,![/assets/type_icons/Fire_Type_Icon.svg](/asse...,Blaze,Solar Power,![/assets/home_images/charmander.png](/assets/...
9,7,Squirtle,1,Normal,Tiny Turtle Pokémon,314,44,48,65,50,64,43,![/assets/type_icons/Water_Type_Icon.svg](/ass...,Torrent,Rain Dish,![/assets/home_images/squirtle.png](/assets/ho...
32,25,Pikachu,1,Normal,Mouse Pokémon,320,35,55,40,50,50,90,![/assets/type_icons/Electric_Type_Icon.svg](/...,Static,Lightning Rod,![/assets/home_images/pikachu.png](/assets/hom...

In [22]:
df.set_index("Name", inplace=True)

In [23]:
new_df = df.loc[mons]
new_df.reset_index(inplace=True)
new_df

,Name,Dex Number,Generation,Status,Species,Stat Total,HP,Attack,Defense,Sp. Attack,Sp. Defense,Speed,Type,Ability,Hidden Ability,Image
0,Charmander,4,1,Normal,Lizard Pokémon,309,39,52,43,60,50,65,![/assets/type_icons/Fire_Type_Icon.svg](/asse...,Blaze,Solar Power,![/assets/home_images/charmander.png](/assets/...
1,Pikachu,25,1,Normal,Mouse Pokémon,320,35,55,40,50,50,90,![/assets/type_icons/Electric_Type_Icon.svg](/...,Static,Lightning Rod,![/assets/home_images/pikachu.png](/assets/hom...
2,Squirtle,7,1,Normal,Tiny Turtle Pokémon,314,44,48,65,50,64,43,![/assets/type_icons/Water_Type_Icon.svg](/ass...,Torrent,Rain Dish,![/assets/home_images/squirtle.png](/assets/ho...
3,Bulbasaur,1,1,Normal,Seed Pokémon,318,45,49,49,65,65,45,![/assets/type_icons/Grass_Type_Icon.svg](/ass...,Overgrow,Chlorophyll,![/assets/home_images/bulbasaur.png](/assets/h...

In [47]:
src_df = new_df[['Name', 'Image', 'Type', 'Ability', 'Hidden Ability']].copy()
src_df

,Name,Image,Type,Ability,Hidden Ability
0,Charmander,![/assets/home_images/charmander.png](/assets/...,![/assets/type_icons/Fire_Type_Icon.svg](/asse...,Blaze,Solar Power
1,Pikachu,![/assets/home_images/pikachu.png](/assets/hom...,![/assets/type_icons/Electric_Type_Icon.svg](/...,Static,Lightning Rod
2,Squirtle,![/assets/home_images/squirtle.png](/assets/ho...,![/assets/type_icons/Water_Type_Icon.svg](/ass...,Torrent,Rain Dish
3,Bulbasaur,![/assets/home_images/bulbasaur.png](/assets/h...,![/assets/type_icons/Grass_Type_Icon.svg](/ass...,Overgrow,Chlorophyll

In [56]:
new_df2 = pd.DataFrame(columns=src_df.columns)
new_df2.loc[0] = src_df.columns
new_df2 = pd.concat([new_df2, src_df])
new_df2 = new_df2.set_index('Name').reset_index()
new_df2

,Name,Image,Type,Ability,Hidden Ability
0,Name,Image,Type,Ability,Hidden Ability
1,Charmander,![/assets/home_images/charmander.png](/assets/...,![/assets/type_icons/Fire_Type_Icon.svg](/asse...,Blaze,Solar Power
2,Pikachu,![/assets/home_images/pikachu.png](/assets/hom...,![/assets/type_icons/Electric_Type_Icon.svg](/...,Static,Lightning Rod
3,Squirtle,![/assets/home_images/squirtle.png](/assets/ho...,![/assets/type_icons/Water_Type_Icon.svg](/ass...,Torrent,Rain Dish
4,Bulbasaur,![/assets/home_images/bulbasaur.png](/assets/h...,![/assets/type_icons/Grass_Type_Icon.svg](/ass...,Overgrow,Chlorophyll